### ISSUE TITLE
Post_limit not defined

### ISSUE THREAD

**Issue by OSINTResearch** [musafir-py/Hidden-Friends-Finder#6]
Running HFF.py aborts with a NameError: name 'post_limit' is not defined.

Found in modules/chrome.py

line 79:
if posts_after_scrolling >= post_limit:
    break

Disabled it and script runs fine.

**Comment by Senator3223** [comment]
Give a closer look to the entire while loop in modules/chrome.py line 71 to 80:
``` 
while True:
        posts_limit = 100
        posts_before_scrolling = posts_after_scrolling
        browser.execute_script("window.scrollTo(0,document.body.scrollHeight);")
        time.sleep(4)
        posts_after_scrolling = len(core.get_elements(browser, **elements.post))
        browser.execute_script("window.scrollTo(0,0);")
        t.update()
        if posts_after_scrolling >= post_limit:
            break
```
As you can see the if statement performs a check on post_limit which does not exist, it is not defined yet. I Guess this is a typo of the developer because there is a variable is defined as posts_limit (plural...) on the second line of the code above (line 72 in chrome.py).

instead of breaking the logic of the program by removing the if-check, I advise to change post_limit to posts_limit within the if-check so the intended logic will still be run.

good luck.

**Comment by IntelTakes** [comment]
Thanks for pointing this out. It was indeed a typo. Fixed.

**Comment by OSINTResearch** [comment]
Closed my PR as well. I'm not really proficient in using git this way, yet. So, it was more of a try :-)
